openapi: 3.0.0
info:
  title: MediConnect API
  version: 1.0.0
  description: Documentación oficial del API de MediConnect.
  contact:
    name: Equipo de Desarrollo MediConnect
servers:
  - url: http://localhost:3000/api
    description: Servidor de Desarrollo Local

tags:
  - name: Traductor
    description: Endpoints de traducción del sistema

# --- RUTAS (ENDPOINTS) ---
paths:
  /traduccion:
    post:
      summary: Traducción dinámica de objetos JSON
      tags: 
        - Traductor
      description: Recibe un objeto JSON arbitrario y una lista de campos, y retorna el objeto con esos campos traducidos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                translate_fields:
                  type: array
                  items:
                    type: string
                  example: ["motivo", "diagnostico"]
                source:
                  type: string
                  example: "es"
                target:
                  type: string
                  example: "en"
                # Campos dinámicos de ejemplo
                id_paciente:
                  type: integer
                  example: 504
                motivo:
                  type: string
                  example: "Dolor de cabeza intenso"
                diagnostico:
                  type: string
                  example: "Migraña severa"
      responses:
        '200':
          description: Traducción exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type: object
                  original:
                    type: object
                  result:
                    type: object
        '400':
          description: Faltan parámetros (translate_fields)
        '500':
          description: Error en el servidor